---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/rust/repo/{{ cookiecutter.repo_name }}/.github/workflows'
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
