---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/rust/repo/{{ cookiecutter.repo_name }}/.github/workflows'
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
    ignore:
      # See https://github.com/dtolnay/rust-toolchain/issues/45 tags aren't used
      # by rust-toolchain. Using a branch name will cause dependabot to suggest
      # which ever branch happens to be the newest
      - dependency-name: "rust-toolchain"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
