---
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"

  rendering:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cookiecutter_directory:
          - rust/repo
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install cookiecutter
      - run: ./render-tests.sh ${{ matrix.cookiecutter_directory }}
      - name: Ensure there are no unaccounted for changes
        run: git diff --quiet --ignore-submodules HEAD

  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # TODO: Add problem matcher?
      - run: yamllint .
