name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"
